language: java
dist:
- trusty
jdk:
- oraclejdk8
branches:
  except:
  - maste
  - dev
addons:
  apt:
    packages:
    - python2.7
before_script:
- unset _JAVA_OPTIONS
script:
- bash deploy.sh
deploy:
  provider: releases
  api_key:
    secure: MnG59i0Fn5Yb8ZssdjwD1SVQijwkvLmDZMQNCtrRzRqjfhvCO3ZJqPEHM1i8eFLgDdoguQXjc45aCqZ/Q9JLlb91K/RgRO83miDLXCtD2GZ41KZNR6KXEeOrnuEC+6pDe30HkvYVeGhaAVs8EOj0XHgngFhDiMm+PFEaNaixFHiJ2VWP9iY0pHvtSjpiQP3RfK6E1txQYZVKR+N19q4U6blBLYRd/9TkOfHwMGn2JZ7slkUTgQ//h9azl99aDj/Gb/VhXw/h4fzv1D28ALt2pUphKQ80fstSGTGJ7kuRVFg8BzF82IntSNCs+b0+ppxJtrNga0BxWF3IJPjIEy1mQkSee8Yv/x6yh7BZPW22s60qBqgEMMqkc/79Aujr4ONShOagM/yFSHh/eNs2B3ZFKsN3VG+QOs1xQwCQs82DcmhM26tEPVTg7qDjOkbTduYUHw61PF2QRPRUVSWDANKGRp+xlyd3/f38AZBt45E/2zqCwpbJmqnMub82k9vy7mt8rYrhm0EZ0H9GI9m5uR6EZqB1mj6rUh5/7beclGTh84mnsVcnAI/OpB2CfJFquOjE9Avnq5l9h7ZmyTBMwkUTgGw7RqDlHZDym/KNjYE9SHiXnpjscwRh5NAHwdz4nCd9gGUzR4s9JzAaZI8Z1TbEhPLvc67BShji0p7avgwfLfg=
  file_glob: true
  file:
  - eufix-*.zip
  overwrite: true
  skip_cleanup: true
  on:
    repo: him007/mipay-extract
    tags: false
